name: Github Action 실행시켜보기

on:
  push:
    branches:
      - master
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 여러 명령어
        run: |
          echo "Good"
          echo "Morning"
